In [1]:
import numpy as np
import pandas as pd
import twitter

In [8]:
corpusfile = pd.read_csv("data/corpus.csv",header=-1)

In [9]:
corpusfile.head()

       0         1                   2
0  apple  positive  126415614616154112
1  apple  positive  126404574230740992
2  apple  positive  126402758403305474
3  apple  positive  126397179614068736
4  apple  positive  126395626979196928

In [10]:
columns = ["topic","label","tweet_id"]

In [11]:
corpusfile.columns = columns

In [12]:
corpusfile.head()

   topic     label            tweet_id
0  apple  positive  126415614616154112
1  apple  positive  126404574230740992
2  apple  positive  126402758403305474
3  apple  positive  126397179614068736
4  apple  positive  126395626979196928

In [13]:
corpusfile.label.value_counts()

neutral       2503
irrelevant    1786
negative       654
positive       570
Name: label, dtype: int64

In [14]:
corpusfile.topic.value_counts()

microsoft    1415
twitter      1404
google       1381
apple        1313
Name: topic, dtype: int64

In [17]:
test = corpusfile.groupby("label")

In [22]:
test.head()

      topic       label            tweet_id
0     apple    positive  126415614616154112
1     apple    positive  126404574230740992
2     apple    positive  126402758403305474
3     apple    positive  126397179614068736
4     apple    positive  126395626979196928
191   apple    negative  126418790706712576
192   apple    negative  126417285559762944
193   apple    negative  126416915664084992
194   apple    negative  126416109212680192
195   apple    negative  126411162622496768
568   apple     neutral  126417484017451009
569   apple     neutral  126415742177513472
570   apple     neutral  126415618625912832
571   apple     neutral  126414657836687362
572   apple     neutral  126410146703351808
1149  apple  irrelevant  126405660308021248
1150  apple  irrelevant  126403953058529280
1151  apple  irrelevant  126402391259103232
1152  apple  irrelevant  126399172495679488
1153  apple  irrelevant  126394266145665025

In [27]:
test2 = corpusfile.groupby(["topic","label"])

In [28]:
test2.head()

          topic       label            tweet_id
0         apple    positive  126415614616154112
1         apple    positive  126404574230740992
2         apple    positive  126402758403305474
3         apple    positive  126397179614068736
4         apple    positive  126395626979196928
191       apple    negative  126418790706712576
192       apple    negative  126417285559762944
193       apple    negative  126416915664084992
194       apple    negative  126416109212680192
195       apple    negative  126411162622496768
568       apple     neutral  126417484017451009
569       apple     neutral  126415742177513472
570       apple     neutral  126415618625912832
571       apple     neutral  126414657836687362
572       apple     neutral  126410146703351808
1149      apple  irrelevant  126405660308021248
1150      apple  irrelevant  126403953058529280
1151      apple  irrelevant  126402391259103232
1152      apple  irrelevant  126399172495679488
1153      apple  irrelevant  126394266145665025
1313     google    positive  126534770095169536
1314     google    positive  126534201880219648
1315     google    positive  126534020367519744
1316     google    positive  126533948925952000
1317     google    positive  126533885109600256
1531     google    negative  126534476875567104
1532     google    negative  126533446293127168
1533     google    negative  126532210210783232
1534     google    negative  126527166195314688
1535     google    negative  126526648928579584
...         ...         ...                 ...
2925  microsoft     neutral  126809228194217984
2926  microsoft     neutral  126808500356644864
2927  microsoft     neutral  126808393892634625
2928  microsoft     neutral  126805369619087360
2929  microsoft     neutral  126805239209803777
3596  microsoft  irrelevant  126807138587783168
3597  microsoft  irrelevant  126806596662726660
3598  microsoft  irrelevant  126806460146524160
3599  microsoft  irrelevant  126801012852916224
3600  microsoft  irrelevant  126800980783271936
4109    twitter    positive  126883590041640960
4110    twitter    positive  126883448173510656
4111    twitter    positive  126883416280006656
4112    twitter    positive  126883364887203840
4113    twitter    positive  126883290782244864
4177    twitter    negative  126883562652844033
4178    twitter    negative  126883300227817472
4179    twitter    negative  126883243726344193
4180    twitter    negative  126882964582838272
4181    twitter    negative  126882934568390656
4255    twitter     neutral  126883719368818688
4256    twitter     neutral  126883711131201536
4257    twitter     neutral  126883672682004480
4258    twitter     neutral  126883640671076352
4259    twitter     neutral  126883630369882112
4902    twitter  irrelevant  126883777938067457
4903    twitter  irrelevant  126883741481177088
4904    twitter  irrelevant  126883583691472896
4905    twitter  irrelevant  126883512073719808
4906    twitter  irrelevant  126883431308197888

[80 rows x 3 columns]

In [32]:
test2.describe()

                     tweet_id                                            \
                        count          mean           std           min
topic     label
apple     irrelevant    164.0  1.259016e+17  3.732127e+14  1.250827e+17
          negative      377.0  1.258727e+17  3.745624e+14  1.251293e+17
          neutral       581.0  1.258747e+17  3.436248e+14  1.250860e+17
          positive      191.0  1.258762e+17  3.525628e+14  1.251652e+17
google    irrelevant    498.0  1.265065e+17  1.610931e+13  1.264840e+17
          negative       61.0  1.265016e+17  1.369020e+13  1.264866e+17
          neutral       604.0  1.265084e+17  1.417722e+13  1.264840e+17
          positive      218.0  1.265024e+17  1.463226e+13  1.264846e+17
microsoft irrelevant    513.0  1.266715e+17  7.719885e+13  1.264849e+17
          negative      138.0  1.266638e+17  8.514703e+13  1.264850e+17
          neutral       671.0  1.266659e+17  8.299523e+13  1.264668e+17
          positive       93.0  1.266824e+17  7.936858e+13  1.264799e+17
twitter   irrelevant    611.0  1.268697e+17  7.356584e+12  1.268544e+17
          negative       78.0  1.268717e+17  7.011109e+12  1.268571e+17
          neutral       647.0  1.268702e+17  7.452826e+12  1.268533e+17
          positive       68.0  1.268720e+17  8.509597e+12  1.268571e+17


                               25%           50%           75%           max
topic     label
apple     irrelevant  1.255773e+17  1.259721e+17  1.262637e+17  1.264057e+17
          negative    1.255834e+17  1.259643e+17  1.261633e+17  1.264188e+17
          neutral     1.256175e+17  1.259430e+17  1.261109e+17  1.264175e+17
          positive    1.256025e+17  1.259302e+17  1.261447e+17  1.264156e+17
google    irrelevant  1.264920e+17  1.265012e+17  1.265226e+17  1.265351e+17
          negative    1.264915e+17  1.264952e+17  1.265145e+17  1.265345e+17
          neutral     1.264961e+17  1.265063e+17  1.265205e+17  1.265351e+17
          positive    1.264912e+17  1.264951e+17  1.265125e+17  1.265348e+17
microsoft irrelevant  1.266159e+17  1.266731e+17  1.267367e+17  1.268071e+17
          negative    1.265949e+17  1.266738e+17  1.267429e+17  1.268030e+17
          neutral     1.266049e+17  1.266760e+17  1.267318e+17  1.268092e+17
          positive    1.266337e+17  1.266956e+17  1.267480e+17  1.268036e+17
twitter   irrelevant  1.268635e+17  1.268693e+17  1.268757e+17  1.268838e+17
          negative    1.268667e+17  1.268709e+17  1.268773e+17  1.268836e+17
          neutral     1.268639e+17  1.268704e+17  1.268764e+17  1.268837e+17
          positive    1.268636e+17  1.268740e+17  1.268789e+17  1.268836e+17

In [33]:
test2.groups

{('apple',
  'irrelevant'): Int64Index([1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158,
             ...
             1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312],
            dtype='int64', length=164),
 ('apple',
  'negative'): Int64Index([191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
             ...
             558, 559, 560, 561, 562, 563, 564, 565, 566, 567],
            dtype='int64', length=377),
 ('apple',
  'neutral'): Int64Index([ 568,  569,  570,  571,  572,  573,  574,  575,  576,  577,
             ...
             1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148],
            dtype='int64', length=581),
 ('apple',
  'positive'): Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
             ...
             181, 182, 183, 184, 185, 186, 187, 188, 189, 190],
            dtype='int64', length=191),
 ('google',
  'irrelevant'): Int64Index([2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205,
             ...
             2684, 2685, 2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693],
            dtype='int64', length=498),
 ('google',
  'negative'): Int64Index([1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541,
             1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552,
             1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563,
             1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574,
             1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585,
             1586, 1587, 1588, 1589, 1590, 1591],
            dtype='int64'),
 ('google',
  'neutral'): Int64Index([1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601,
             ...
             2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195],
            dtype='int64', length=604),
 ('google',
  'positive'): Int64Index([1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322,
             ...
             1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530],
            dtype='int64', length=218),
 ('microsoft',
  'irrelevant'): Int64Index([3596, 3597, 3598, 3599, 3600, 3601, 3602, 3603, 3604, 3605,
             ...
             4099, 4100, 4101, 4102, 4103, 4104, 4105, 4106, 4107, 4108],
            dtype='int64', length=513),
 ('microsoft',
  'negative'): Int64Index([2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796,
             ...
             2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924],
            dtype='int64', length=138),
 ('microsoft',
  'neutral'): Int64Index([2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934,
             ...
             3586, 3587, 3588, 3589, 3590, 3591, 3592, 3593, 3594, 3595],
            dtype='int64', length=671),
 ('microsoft',
  'positive'): Int64Index([2694, 2695, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704,
             2705, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715,
             2716, 2717, 2718, 2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726,
             2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737,
             2738, 2739, 2740, 2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748,
             2749, 2750, 2751, 2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759,
             2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770,
             2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 2780, 2781,
             2782, 2783, 2784, 2785, 2786],
            dtype='int64'),
 ('twitter',
  'irrelevant'): Int64Index([4902, 4903, 4904, 4905, 4906, 4907, 4908, 4909, 4910, 4911,
             ...
             5503, 5504, 5505, 5506, 5507, 5508, 5509, 5510, 5511, 5512],
            dtype='int64', length=611),
 ('twitter',
  'negative'): Int64Index([4177, 4178, 4179, 4180, 4181, 4182, 4183, 4184, 4185, 4186, 4187,
             4188, 4189, 4190, 4191, 4192, 4193, 4194, 4195, 4196, 4197, 4198,
             4199, 4200, 4201, 4202, 4203, 4204, 4205, 4206, 4207, 4208, 4209,
             4210, 4211, 4212, 4213, 4214, 4215, 4216, 4217, 4218, 4219, 4220,
             4221, 4222, 4223, 4224, 4225, 4226, 4227, 4228, 4229, 4230, 4231,
             4232, 4233, 4234, 4235, 4236, 4237, 4238, 4239, 4240, 4241, 4242,
             4243, 4244, 4245, 4246, 4247, 4248, 4249, 4250, 4251, 4252, 4253,
             4254],
            dtype='int64'),
 ('twitter',
  'neutral'): Int64Index([4255, 4256, 4257, 4258, 4259, 4260, 4261, 4262, 4263, 4264,
             ...
             4892, 4893, 4894, 4895, 4896, 4897, 4898, 4899, 4900, 4901],
            dtype='int64', length=647),
 ('twitter',
  'positive'): Int64Index([4109, 4110, 4111, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119,
             4120, 4121, 4122, 4123, 4124, 4125, 4126, 4127, 4128, 4129, 4130,
             4131, 4132, 4133, 4134, 4135, 4136, 4137, 4138, 4139, 4140, 4141,
             4142, 4143, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4152,
             4153, 4154, 4155, 4156, 4157, 4158, 4159, 4160, 4161, 4162, 4163,
             4164, 4165, 4166, 4167, 4168, 4169, 4170, 4171, 4172, 4173, 4174,
             4175, 4176],
            dtype='int64')}